### ISSUE TITLE
The application can't be opened

### ISSUE THREAD

**Issue by hawkkiller** [tsinis/colors_ai#182]
#### Description
Downloaded and launched the app. I guess it is a bug.
<img width="372" alt="image" src="https://user-images.githubusercontent.com/62852417/229187336-6019a3eb-6e91-48df-9ba6-2bcb87bba6b9.png">

MacOS
<img width="469" alt="image" src="https://user-images.githubusercontent.com/62852417/229187538-f0e45da6-42ef-481e-8e57-cc58e6b901d0.png">

**Comment by tsinis** [comment]
@hawkkiller thanks for the report. It may be related to the fact that the builds are not signed, but I will take a look anyway.

**Comment by tsinis** [comment]
[@hawkkiller](https://github.com/hawkkiller) I don't have access to the device with macOS without MDM and with full admin rights now, but I can confirm that issue exists. I removed macOS builds in the Releases section. You can always build a macOS release for your personal use with `flutter build macos` command & providing proper team in Xcode workspace settings. I will monitor this problem in future releases when I get my hands on a macOS device without rights restrictions. Thanks for reporting again!
