### ISSUE TITLE
Was versionCode decreased after v2.1.0?

### ISSUE THREAD

**Issue by IzzySoft** [tsinis/colors_ai#241]
I just was wondering why updates to the latest version failed. Looks like v2.2.1 has `versionCode: 13` while v2.1.0 had `versionCode: 1011`, so Android considers it a downgrade. A closer look reveals: You no longer provide per-ABI builds but just a single "universal APK", hence that "Flutter rule" setting the `versionCode` to `1000 + versionCode` for armeabi no longer applies.

May I ask to make per-ABI builds available again? That would also reduce the download size significantly (per-ABI was ~8MB, universal now is at ~24MB). That done, you could also [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link to [your app in my repo](https://apt.izzysoft.de/packages/is.tsin.colors_ai.colors_ai/) next to the one from Google, as then recent versions would become available there again (currently they are removed as being "older") :wink:

Thanks in advance!

**Comment by tsinis** [comment]
@IzzySoft Thanks for raising the issue, I definitely can do such an adjustment, however, I'm not sure about when the next release will be so you can actually benefit from it :-/. Let's see, thanks again!

**Comment by IzzySoft** [comment]
Thanks for your fast reply, @tsinis! I'd say a day or a week or even a month would not matter much now. It just came up at my end as there were no updates for more than a year – at which point one of my scanners reports to me to take a look :wink:

And basically, no much change needed. You could even simply add the armeabi build for know (based on the same commit of that last tag – so no new release needed), and everything else can be done later.

**Comment by IzzySoft** [comment]
Please give me a ping here when I shall take another look. Everything at your pace of course, no pressure – I just want to make sure in the end it's not me having missed your fix :wink:

**Comment by tsinis** [comment]
> Please give me a ping here when I shall take another look. Everything at your pace of course, no pressure – I just want to make sure in the end it's not me having missed your fix :wink:

Sure, I will, no worries.

**Comment by tsinis** [comment]
@IzzySoft please take a look at [release 2.2.2](https://github.com/tsinis/colors_ai/releases/tag/2.2.2). Release CI is now using [split-per-abi](https://github.com/tsinis/colors_ai/blob/main/.github/workflows/release.yaml#L94-L105) flag.

**Comment by IzzySoft** [comment]
Looks good:

```
$ iod repo get is.tsin.colors_ai.colors_ai
is.tsin.colors_ai.colors_ai: looking for 'https://api.github.com/repos/tsinis/colors_ai/releases'
is.tsin.colors_ai.colors_ai: checking tag '2.2.2'
is.tsin.colors_ai.colors_ai: lastRelNo set to '2.2.2', checking for files
is.tsin.colors_ai.colors_ai: Upstream file date (2023-08-19 21:26) is newer than ours (2022-07-09 02:00).
is.tsin.colors_ai.colors_ai: returning ['2.2.2','https://github.com/tsinis/colors_ai/releases/download/2.2.2/colors-ai-armeabi-v7a.apk',1692473206]
is.tsin.colors_ai.colors_ai: 2.1.0/2.2.2, https://github.com/tsinis/colors_ai/releases: https://github.com/tsinis/colors_ai/releases/download/2.2.2/colors-ai-armeabi-v7a.apk
- Grabbing update for is.tsin.colors_ai.colors_ai: OK
- Checking 'repo/is.tsin.colors_ai.colors_ai_1014.apk' for libraries and malware …
is.tsin.colors_ai.colors_ai: check if repo contains FUNDING.yml
is.tsin.colors_ai.colors_ai: looking for 'https://api.github.com/repos/tsinis/colors_ai/contents/.github'
is.tsin.colors_ai.colors_ai: looking for 'https://api.github.com/repos/tsinis/colors_ai/contents/'
is.tsin.colors_ai.colors_ai: no FUNDING.yml detected.
is.tsin.colors_ai.colors_ai: no Fastlane configured, skipping Fastlane check.
```

And to answer unasked questions on the last 2 lines:

* [FUNDING.yml](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository) lets you maintain donation links
* [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) lets you maintain description & graphics to present your app

So all fine, thanks a lot! Feel free to close this issue (as it's solved) or leave it open adding questions left on your end.

**Comment by tsinis** [comment]
@IzzySoft Yes it's correct I don't have a FUNDING.yml in this repo and I'm not using Fastlane in any of my projects (GitHub workflows + Codemagic are enough for my needs). Thanks, I'm closing.

**Comment by IzzySoft** [comment]
> I'm not using Fastlane in any of my projects

If you had, my updater would fetch that along with new releases. Of course you can also ping me if changes are needed.

**Comment by tsinis** [comment]
> > I'm not using Fastlane in any of my projects
> 
> If you had, my updater would fetch that along with new releases. Of course you can also ping me if changes are needed.

Sure I would change my mind - I will let you know. Thanks.
