### ISSUE TITLE
Snap version shows a blank window on Ubuntu 24.04 with Wayland

### ISSUE THREAD

**Issue by rolandixor** [tsinis/colors_ai#357]
#### Description

The app launches, but the window is blank.

#### Steps To Reproduce

1. Open the application under a Wayland environment

#### Expected Behavior

The app works as normal.

#### Screenshots

![Screenshot_20240515_140331](https://github.com/tsinis/colors_ai/assets/558147/523754c4-ef46-4e74-872f-3c3df3b55983)

#### Additional Context

When running the binary downloaded from here (Github), it works just fine.

**Comment by tsinis** [comment]
Hello @rolandixor, thank you for your feedback! I'm pleased to hear that you're using the app and I hope you like it! I believe the snap-based app was built with core 18, which might explain why it's not functioning with 24. I will investigate the issue and see if there's a fix I can apply. I'll keep you updated and will keep this issue open as a reminder. However, please be aware that a resolution may not be immediate, as I am currently preoccupied with my primary work projects.

**Comment by tsinis** [comment]
Hey @rolandixor, thanks for the report, but this repository is being archived due to a lack of time and the presence of significant technical debt. Thank you for your understanding in advance!
